runtime: python37

env_variables:
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@35.232.187.34
  CLOUD_SQL_CONNECTION_NAME: geophotoalbum:us-central1:geo-photo-album-db
  CLOUDSQL_USER: postgres
  CLOUDSQL_PASSWORD: postgresPW  
  # DB_USER: postgres
  # DB_PASS: postgresPW 
  # DB_NAME: geo-photo-album-db


# saw the below in a tutorial but not sure if/why i need:
# env: flex
# entrypoint: gunicorn -b :$PORT main:app

# runtime_config:
#   python_version: 3