"""add description to Photo model

Revision ID: f24dbff8c76a
Revises: c2bca4d27587
Create Date: 2021-08-04 13:15:39.323091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24dbff8c76a'
down_revision = 'c2bca4d27587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'description')
    # ### end Alembic commands ###
